services:
  postgres-graph:
    container_name: postgres-graph
    image: postgres:13
    environment:
      POSTGRES_USER: graph
      POSTGRES_PASSWORD: letmein
      POSTGRES_DB: graph
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - protocol

  graph-node:
    container_name: graph-node
    image: graphprotocol/graph-node
    ports:
      - "8000:8000"
      - "8020:8020"
      - "8030:8030"
      - "8040:8040"
    environment:
      ipfs: 'http://rust-ipfs:8081'
      postgres_host: postgres-graph
      postgres_user: graph
      postgres_pass: letmein
      postgres_db: graph
      ethereum: 'private:http://bootnode:8545'
    depends_on:
      - postgres-graph
    networks:
      - protocol

volumes:
  pgdata:
    driver: local

networks:
  protocol:
    external: true

