version: "3.4"

services:
  besu_node_1:
    container_name: besu_node_1
    image: hyperledger/besu:23.4.4
    user: "1000:1000"
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "sleep 10; /opt/besu/bin/besu --data-path=/opt/besu/data --metrics-enabled --metrics-host=0.0.0.0 --metrics-port=9545 --genesis-file=/opt/besu/genesis.json --rpc-http-enabled --rpc-ws-enabled --rpc-ws-port=6174 --rpc-ws-host=0.0.0.0 --rpc-http-api=ETH,NET,QBFT,TXPOOL --host-allowlist='*' --rpc-http-cors-origins='all' --rpc-http-port=8545 --rpc-http-host=0.0.0.0 --min-gas-price=0 --rpc-http-max-batch-size=10",
      ]
    volumes:
      - ./.docker/besu/genesis.json:/opt/besu/genesis.json
      - ./.docker/besu/node1/data:/opt/besu/data
    ports:
      - "8545:8545"
      - "30303:30303"
      - "6174:6174"
    networks:
      protocol:
        ipv4_address: 172.16.239.10

  besu_node_2:
    container_name: besu_node_2
    image: hyperledger/besu:23.4.4
    user: "1000:1000"
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "sleep 10; /opt/besu/bin/besu --data-path=/opt/besu/data --metrics-enabled --metrics-host=0.0.0.0 --metrics-port=9546 --genesis-file=/opt/besu/genesis.json --bootnodes='enode://5b609a41c3b2709084a1dc68df20906b109c6e6eafcf2f97ae744fe4f8e8f91389ce565ea2881b6d9e101df0d1624929f6396acce22b3ab2907d2bbb30328f7f@172.16.239.10:30303' --p2p-port=30304 --rpc-http-enabled --rpc-ws-enabled --rpc-ws-port=6175 --rpc-http-api=ETH,NET,IBFT,TXPOOL --host-allowlist='*' --rpc-http-cors-origins='all' --rpc-http-port=8546 --rpc-http-host=0.0.0.0 --min-gas-price=0",
      ]
    volumes:
      - ./.docker/besu/genesis.json:/opt/besu/genesis.json
      - ./.docker/besu/node2/data:/opt/besu/data
      - ./.docker/besu/log-config.xml:/config/log-config.xml
    ports:
      - "8546:8546"
      - "30304:30304"
      - "6175:6175"
    depends_on:
      - besu_node_1
    networks:
      protocol:
        ipv4_address: 172.16.239.11

  besu_node_3:
    container_name: besu_node_3
    image: hyperledger/besu:23.4.4
    user: "1000:1000"
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "sleep 10; /opt/besu/bin/besu --data-path=/opt/besu/data --metrics-enabled --metrics-host=0.0.0.0 --metrics-port=9547 --genesis-file=/opt/besu/genesis.json --bootnodes='enode://5b609a41c3b2709084a1dc68df20906b109c6e6eafcf2f97ae744fe4f8e8f91389ce565ea2881b6d9e101df0d1624929f6396acce22b3ab2907d2bbb30328f7f@172.16.239.10:30303' --p2p-port=30305 --rpc-http-enabled --rpc-ws-enabled --rpc-ws-port=6176 --rpc-http-api=ETH,NET,QBFT,TXPOOL --host-allowlist='*' --rpc-http-cors-origins='all' --rpc-http-port=8547 --rpc-http-host=0.0.0.0 --min-gas-price=0",
      ]
    volumes:
      - ./.docker/besu/genesis.json:/opt/besu/genesis.json
      - ./.docker/besu/node3/data:/opt/besu/data
      - ./.docker/besu/log-config.xml:/config/log-config.xml
    ports:
      - "8547:8547"
      - "30305:30305"
      - "6176:6176"
    depends_on:
      - besu_node_1
    networks:
      protocol:
        ipv4_address: 172.16.239.12

  besu_node_4:
    container_name: besu_node_4
    image: hyperledger/besu:23.4.4
    user: "1000:1000"
    entrypoint:
      [
        "/bin/bash",
        "-c",
        "sleep 10; /opt/besu/bin/besu --data-path=/opt/besu/data --metrics-enabled --metrics-host=0.0.0.0 --metrics-port=9548 --genesis-file=/opt/besu/genesis.json --bootnodes='enode://5b609a41c3b2709084a1dc68df20906b109c6e6eafcf2f97ae744fe4f8e8f91389ce565ea2881b6d9e101df0d1624929f6396acce22b3ab2907d2bbb30328f7f@172.16.239.10:30303' --p2p-port=30306 --rpc-http-enabled --rpc-ws-enabled --rpc-ws-port=61747 --rpc-http-api=ETH,NET,QBFT,TXPOOL --host-allowlist='*' --rpc-http-cors-origins='all' --rpc-http-port=8548 --rpc-http-host=0.0.0.0 --min-gas-price=0",
      ]
    volumes:
      - ./.docker/besu/genesis.json:/opt/besu/genesis.json
      - ./.docker/besu/node4/data:/opt/besu/data
      - ./.docker/besu/log-config.xml:/config/log-config.xml
    ports:
      - "8548:8548"
      - "30306:30306"
      - "61747:61747"
    depends_on:
      - besu_node_1
    networks:
      protocol:
        ipv4_address: 172.16.239.13

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - protocol

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3005:3000"
    networks:
      - protocol

  explorer:
    container_name: explorer
    image: alethio/ethereum-lite-explorer
    ports:
      - "80:80"
    environment:
      - APP_NODE_URL=http://localhost:8545
    depends_on:
      - besu_node_1
    networks:
      - protocol

  minio:
    container_name: minio
    image: quay.io/minio/minio
    environment:
      - MINIO_ROOT_USER=Admin
      - MINIO_ROOT_PASSWORD=Astronalta@24
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"
    networks:
      - protocol
    restart: always


  db:
    image: postgres:latest
    container_name: db_postgrees
    env_file:
      - ./.env
    volumes:
      - postgree_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      protocol:
        ipv4_address: 172.16.239.14

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    volumes:
      - vault_data:/.docker/vault/data
      - ./vault-config.json:/.docker/vault/config.json
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/.docker/vault/config.json
    networks:
      protocol:
        ipv4_address: 172.16.239.15

volumes:
  grafana_data:
    driver: local
  postgree_data:
    driver: local
  pnpm-store:
    driver: local
  prometheus_data:
    driver: local
  vault_data:
    driver: local
  minio-data:
    driver: local

networks:
  protocol:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24
