services:
  wallet-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loyahub-wallet-engine
    ports:
      - "8084:8084"
    networks:
      protocol:
        aliases:
          - wallet-engine
    environment:
      RUST_LOG: info
      VAULT_URL: http://vault:8200 

networks:
  protocol:
    external: true
