POST http://localhost:3001/api/v1/points/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJzdWIiOjEsImlhdCI6MTcwNjk5MTk5NiwiZXhwIjoxNzA2OTkyMjU2fQ.P4hi0y_TNjQFXUcmqiKZCLuLWS0Q1iswGaKDSgGfZJU

{
    "clientId": 1,
    "points": 100
}

